In [1]:
import pandas as pd
import numpy as np
from impute_df import impute_missing_values

In [2]:
# Load the data from the csv file
df = pd.read_csv('Protenus Sales Training Data.csv')
df.head()

,Snapshot_Date,Opportunity_ID,Opportunity_Stage,Opportunity_Type,Opportunity_Annual_Amount,Opportunity_Created_Date,Opportunity_Close_Date,Opportunity_Product,Account_Electronic_Medical_Record_System,Account_Hospital_Type,Account_Fiscal_Year_End,Account_State,Account_Zip_Code,Account_Number_of_Hospitals,Account_Number_of_Beds,Account_Number_of_Affiliated_Physicians,Account_Number_of_Employee,Account_Cash_on_Hand,Account_Total_Patient_Revenue,Account_Net_Patient_Revenue
0,10/1/2019,0064100000TL1Fw,Stage 3 - Pricing,New Business,NaN,9/12/2018,11/12/2019,Diversion Monitoring,Epic,Childrens Hospital,12/31/2023,OH,43205.0,2.0,694.0,2196.0,7282.0,85077078.0,3.652792e+09,2.048661e+09
1,10/1/2019,0064100000TKWAx,Stage 3 - Pricing,New Business,NaN,9/7/2018,12/12/2019,Privacy Monitoring,Epic,Health System,NaN,HI,96813.0,4.0,602.0,1829.0,4443.0,-242188.0,3.560499e+09,1.340713e+09
2,10/1/2019,0064100000TKw69,Stage 2 - Scoping,New Business,NaN,9/11/2018,4/15/2020,Diversion Monitoring,Epic,Health System,NaN,MI,49503.0,10.0,1901.0,4000.0,NaN,982985681.0,7.869236e+09,3.290488e+09
3,10/1/2019,0064100000TK0q9,Stage 2 - Scoping,New Business,NaN,8/29/2018,2/22/2020,Diversion Monitoring,Epic,Health System,NaN,OH,43604.0,12.0,1594.0,2481.0,NaN,165601560.0,1.075654e+10,2.468940e+09
4,10/1/2019,0064100000QhXXx,Stage 3 - Pricing,New Business,NaN,6/26/2018,12/10/2019,Privacy Monitoring,Epic,Health System,NaN,WI,53226.0,10.0,1259.0,2666.0,8197.0,20765609.0,1.024796e+10,3.881722e+09

In [3]:
# Drop all the old data with missing annual amounts
df['Snapshot_Date'] = pd.to_datetime(df['Snapshot_Date'])
df = df[df['Snapshot_Date'] >= '2020-08-01']
print(df.shape)

(7542, 20)

In [4]:
df = impute_missing_values(df)
df.head()

In [5]:
df['Month'] = df['Snapshot_Date'].dt.month - 1
df.loc[df['Snapshot_Date'].dt.month == 1, 'Month'] = 12
df['Year'] = df['Snapshot_Date'].dt.year
df.loc[df['Snapshot_Date'].dt.month == 1, 'Year'] = df['Year'] - 1

# Create a new column for quarters where 1,2,3 = Q1, 4,5,6 = Q2, 7,8,9 = Q3, 10,11,12 = Q4
df['Quarter'] = np.where(df['Month'].isin([1,2,3]), 'Q1',
                         np.where(df['Month'].isin([4,5,6]), 'Q2',
                                  np.where(df['Month'].isin([7,8,9]), 'Q3',
                                           np.where(df['Month'].isin([10,11,12]), 'Q4', 'NA'))))
df.head()

,Snapshot_Date,Opportunity_ID,Opportunity_Stage,Opportunity_Type,Opportunity_Annual_Amount,Opportunity_Created_Date,Opportunity_Close_Date,Opportunity_Product,Account_Electronic_Medical_Record_System,Account_Hospital_Type,...,Account_Number_of_Hospitals,Account_Number_of_Beds,Account_Number_of_Affiliated_Physicians,Account_Number_of_Employee,Account_Cash_on_Hand,Account_Total_Patient_Revenue,Account_Net_Patient_Revenue,Month,Year,Quarter
1302,2020-08-01,0064100000TL1Fw,Stage 2 - Scoping,New Business,317822.6165,9/12/2018,6/28/2021,Diversion Monitoring,Epic,Childrens Hospital,...,2.0,694.0,2196.0,7282.0,85077078.0,3.652792e+09,2.048661e+09,7,2020,Q3
1303,2020-08-01,0064100000TKw69,Stage 2 - Scoping,New Business,412829.9260,9/11/2018,12/16/2020,Diversion Monitoring,Epic,Health System,...,10.0,1901.0,4000.0,NaN,982985681.0,7.869236e+09,3.290488e+09,7,2020,Q3
1304,2020-08-01,0064100000TK0q9,Stage 2 - Scoping,New Business,383035.0469,8/29/2018,3/22/2021,Diversion Monitoring,Epic,Health System,...,12.0,1594.0,2481.0,NaN,165601560.0,1.075654e+10,2.468940e+09,7,2020,Q3
1305,2020-08-01,0064100000TI5Vc,Stage 4 - Verbal / VOC,New Business,619815.4380,8/2/2018,10/30/2020,Diversion Monitoring,Epic,Health System,...,7.0,978.0,1719.0,6338.0,293685873.0,1.629606e+10,2.353002e+09,7,2020,Q3
1306,2020-08-01,0064100000QhXXx,Stage 3 - Pricing,New Business,388269.5616,6/26/2018,9/17/2020,Privacy Monitoring,Epic,Health System,...,10.0,1259.0,2666.0,8197.0,20765609.0,1.024796e+10,3.881722e+09,7,2020,Q3

In [6]:
# Create a quarterly dataframe, where for each 'Opportunity_ID' the data is aggregated by quarter and year. 
df['Year_Quarter'] = df['Year'].astype(str) + df['Quarter'].astype(str)

quarterly_df = df.sort_values('Snapshot_Date').groupby(['Opportunity_ID', 'Year_Quarter']).last().reset_index()

quarterly_df.head()

,Opportunity_ID,Year_Quarter,Snapshot_Date,Opportunity_Stage,Opportunity_Type,Opportunity_Annual_Amount,Opportunity_Created_Date,Opportunity_Close_Date,Opportunity_Product,Account_Electronic_Medical_Record_System,...,Account_Number_of_Hospitals,Account_Number_of_Beds,Account_Number_of_Affiliated_Physicians,Account_Number_of_Employee,Account_Cash_on_Hand,Account_Total_Patient_Revenue,Account_Net_Patient_Revenue,Month,Year,Quarter
0,0061K00000b3JMy,2020Q3,2020-10-01,Stage 2 - Scoping,New Business,167838.3211,3/5/2019,3/31/2021,Privacy Monitoring,Other,...,NaN,296.0,684.0,NaN,21723248.0,1.471406e+09,3.705945e+08,9,2020,Q3
1,0061K00000b3JMy,2020Q4,2021-01-01,Stage 2 - Scoping,New Business,167838.3211,3/5/2019,6/30/2021,Privacy Monitoring,Other,...,NaN,296.0,684.0,NaN,21723248.0,1.471406e+09,3.705945e+08,12,2020,Q4
2,0061K00000b3JMy,2021Q1,2021-04-01,Closed Lost,New Business,167838.3211,3/5/2019,3/30/2021,Privacy Monitoring,Other,...,NaN,296.0,684.0,NaN,21723248.0,1.471406e+09,3.705945e+08,3,2021,Q1
3,0061K00000b3Qsm,2020Q3,2020-10-01,Stage 3 - Pricing,New Business,418991.1971,3/7/2019,4/16/2021,Privacy Monitoring,Epic,...,21.0,2708.0,3670.0,12464.0,160091963.0,1.345325e+10,2.802628e+09,9,2020,Q3
4,0061K00000b3Qsm,2020Q4,2021-01-01,Stage 3 - Pricing,New Business,418991.1971,3/7/2019,9/16/2021,Privacy Monitoring,Epic,...,21.0,2708.0,3670.0,12464.0,160091963.0,1.345325e+10,2.802628e+09,12,2020,Q4

In [7]:
# Create a column for the 'Opportunity_Annual_Amount' of the previous quarter for each 'Opportunity_ID'
quarterly_df['Opportunity_Annual_Amount_Prev_Quarter'] = quarterly_df.groupby('Opportunity_ID')['Opportunity_Annual_Amount'].shift(1)
quarterly_df.head()

# Filter the data to only include data where 'Opportunity_Stage' is 'Closed Won'
quarterly_df_won = quarterly_df[quarterly_df['Opportunity_Stage'] == 'Closed Won']
quarterly_df_won.head()

# Drop data where 'Opportunity_Annual_Amount' is null or 0
# quarterly_df_won = quarterly_df_won[quarterly_df_won['Opportunity_Annual_Amount'] > 0]
# quarterly_df_won.head()

,Opportunity_ID,Year_Quarter,Snapshot_Date,Opportunity_Stage,Opportunity_Type,Opportunity_Annual_Amount,Opportunity_Created_Date,Opportunity_Close_Date,Opportunity_Product,Account_Electronic_Medical_Record_System,...,Account_Number_of_Beds,Account_Number_of_Affiliated_Physicians,Account_Number_of_Employee,Account_Cash_on_Hand,Account_Total_Patient_Revenue,Account_Net_Patient_Revenue,Month,Year,Quarter,Opportunity_Annual_Amount_Prev_Quarter
12,0061K00000b3Qsm,2022Q4,2023-01-01,Closed Won,New Business,383667.85170,3/7/2019,12/2/2022,Privacy Monitoring,Epic,...,2708.0,3670.0,12464.0,160091963.0,1.345325e+10,2.802628e+09,12,2022,Q4,396827.9728
51,0061K00000c4njV,2023Q2,2023-06-01,Closed Won,New Business,523803.90910,3/1/2019,5/18/2023,Diversion Monitoring,Epic,...,4816.0,6663.0,23378.0,159205691.0,2.118838e+10,6.505254e+09,5,2023,Q2,523803.9091
62,0061K00000cP8i8,2020Q3,2020-10-01,Closed Won,New Business,376921.72130,5/1/2019,9/15/2020,Compliance Analytics,Epic,...,440.0,2841.0,5674.0,139653000.0,3.156241e+09,1.194338e+09,9,2020,Q3,NaN
63,0061K00000cPETF,2020Q3,2020-08-01,Closed Won,Existing Business,94503.85434,5/2/2019,7/23/2020,Diversion Monitoring,Other,...,431.0,NaN,2825.0,NaN,NaN,NaN,7,2020,Q3,NaN
72,0061K00000chhPZ,2020Q3,2020-10-01,Closed Won,New Business,139759.99490,3/26/2019,9/30/2020,Privacy Monitoring,Epic,...,575.0,1550.0,7600.0,35101721.0,4.250111e+09,1.201182e+09,9,2020,Q3,NaN

In [8]:
print(df.shape)
print(quarterly_df.shape)
print(quarterly_df_won.shape)

(7542, 24)
(2925, 25)
(145, 25)

In [9]:
# Calculate the difference between the 'Opportunity_Annual_Amount' of the current quarter and the previous quarter
quarterly_df_won['Opportunity_Annual_Amount_Diff'] = quarterly_df_won['Opportunity_Annual_Amount'] - quarterly_df_won['Opportunity_Annual_Amount_Prev_Quarter']
quarterly_df_won.head()

# Calculate the average of 'Opportunity_Annual_Amount_Diff' for all 'Opportunity_ID's
Q_diff = quarterly_df_won['Opportunity_Annual_Amount_Diff'].mean()

# Calculate the average of 'Opportunity_Annual_Amount' and get a percentage of the average difference
Q_avg = quarterly_df_won['Opportunity_Annual_Amount'].mean()

print(Q_diff)
print(Q_avg)
print (100* Q_diff/Q_avg)

-20050.68141172414
192467.10714193105
-10.417718491990511

C:\Users\odani\AppData\Local\Temp\ipykernel_15272\1376284020.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  quarterly_df_won['Opportunity_Annual_Amount_Diff'] = quarterly_df_won['Opportunity_Annual_Amount'] - quarterly_df_won['Opportunity_Annual_Amount_Prev_Quarter']

The above would mean that on average, the closing deal goes down by 11 percent compared to the previous quarter estimation.

In [10]:
# Count the number of 'Opportunity_ID's that only appear once in the quarterly data
ids_once = quarterly_df['Opportunity_ID'].value_counts()
ids_once = ids_once[ids_once == 1].index

# Create a subset of the data where 'Opportunity_ID' only appears one time
quarter_df_once = quarterly_df[quarterly_df['Opportunity_ID'].isin(ids_once)]

# Count how many in quarter_df_once have a 'Closed Won' 'Opportunity_Stage'
stages = quarter_df_once['Opportunity_Stage'].value_counts()
Closed_singleQ = stages['Closed Won']

# Count how many 'Closed Won' 'Opportunity_ID's there are in the quarterly data
Closed_total = quarterly_df_won['Opportunity_ID'].nunique()

print(Closed_singleQ)
print(Closed_total)
print(100*Closed_singleQ/(Closed_total))

29
145
20.0

The above indicated that 29 out of the total 142 closed deals were opened and closed in the same quarter. This is ~20% of all deals.

In [11]:
# Count total number of quarters in the data
total_quarters = quarterly_df['Year_Quarter'].nunique()
print(total_quarters)

# Count the average amount of closings per quarter
avg_closings = Closed_total/total_quarters
print(avg_closings)

# Count the average annual amount per quarter
avg_annual = avg_closings * Q_avg
print(avg_annual)

# Count how many 'Closed Won' cases there were for each 'Year_Quarter'
Closed_quarters = quarterly_df_won['Year_Quarter'].value_counts()
print(Closed_quarters)

12
12.083333333333334
2325644.2112983335
2022Q4    22
2021Q4    22
2020Q4    13
2023Q1    12
2021Q3    12
2022Q2    12
2023Q2    11
2020Q3    11
2022Q3    11
2021Q2     8
2021Q1     6
2022Q1     5
Name: Year_Quarter, dtype: int64

There are a total of 12 quarters, where on average there are ~12 closing per quarter.

In [12]:
# To account for 'Closed_singleQ', calculate its quarterly effect
prob_singleQ = Closed_singleQ/total_quarters
avg_singleQ = prob_singleQ * Q_avg
print(avg_singleQ)

# To account for 'Q_diff', calculate its quarterly effect
avg_Q_diff = Q_diff * avg_closings
print(avg_Q_diff)

# Calculate the total quarterly effect
total_avg_Q_eff = avg_singleQ + avg_Q_diff
print (100*total_avg_Q_eff/avg_annual)

465128.84225966665
-242279.06705833337
9.582281508009487

In [13]:
# Save the quarterly_df as a csv file
quarterly_df['Opportunity_Annual_Amount_Diff'] = quarterly_df['Opportunity_Annual_Amount'] - quarterly_df['Opportunity_Annual_Amount_Prev_Quarter']
quarterly_df.to_csv('quarterly_df.csv', index=False)

The total 'Fix' for both the effect of 'new appearing and closing deals' and the error in the value projection should amount to +9.5% .